name: leitor_acessivel
description: "Aplicativo acessível para leitura de arquivos EPUB, PDF e DOC."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  file_selector: ^0.9.3
  open_file: ^3.3.2
  permission_handler: ^11.0.1
  firebase_core: ^2.28.0
<<<<<<< HEAD
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.16.0
  google_sign_in: ^6.3.0
=======
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.16.0
>>>>>>> 7d3cdea0458b658c32447f4485123d900f153cf2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/epubs/
    - assets/fonts/
<<<<<<< HEAD
    - assets/icons/
=======
>>>>>>> 7d3cdea0458b658c32447f4485123d900f153cf2
